### ISSUE TITLE
Load more button is shown ; but only 1 tx

### ISSUE THREAD

**Issue by frankTheTank72** [signum-network/signum-xt-wallet-fork#16] opened 2022-02-12 08:35 UTC
**Describe the bug**
My wallet has one transaction - but still the button "load more" os shown

**Screenshots**
![grafik](https://user-images.githubusercontent.com/39116221/153703991-8ac768cc-5ddd-4667-a0a1-59ef35a9929b.png)

**Browser (please complete the following information):**
Firefox

**Comment by frankTheTank72** [comment] 2022-02-12 09:02
Button went away after thr tx was not longer pending

**Comment by shefass** [comment] 2022-02-13 12:53
fix #25

**Comment by ohager** [comment] 2022-02-13 15:31
This is not a bug

**Comment by ohager** [comment] 2022-02-13 17:44
Fixed in #25

**Closed as completed by ohager** 2022-02-13 17:44 UTC
Labels: enhancement
